# Generated by Django 4.2.7 on 2025-02-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='/home/shikhar/django_projects/blogWebsite/blog/static/blog/images/defpic.png', upload_to='profile_pic/'),
        ),
    ]
